version: '2'
services:
  web:
    image: nginx
    depends_on:
      - db
      - redis
    dns: 8.8.8.8
    ports: 
      - "8081:80"
    networks:
      - default
      - practice2_default
  redis:
    image: redis
  db:
    image: postgres

networks:
  practice2_default:
    external: true